config/routes.rb
Exchange::Application.routes.draw do

  resources :gambles

  root 'pages#home'

  devise_for :admins
  devise_for :users

  resources :transactions
  resources :orders
  resources :addresses

  get "pages/home"
  get "pages/status"
  get "pages/about"
  get "pages/contact"
  get "pages/finances"

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/gamble.rb
class Gamble < ActiveRecord::Base
  belongs_to :user
  validates_numericality_of :amount, less_than_or_equal_to: :check_user_amount

  #Right now its set to server balance cause of fee's not being counted.
  def check_user_amount
    self.user.check_server_balance
  end

  def win_or_lose
    number = self.created_at.to_f.to_s[-1].to_i
    if number >= 6
      self.won = true
    else 
      self.won = false
    end
    self.save
  end

  def payout
    if self.won == true
      btcserver.move("1337", self.user_id.to_s, (self.amount * 2), 0)
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :trades
  belongs_to :user

  def order_status
    start_time = self.created_at
    end_time = start_time + 1.day
    if Time.now.between?(start_time, end_time)
      self.status = "pending"
    else
      self.status = "cancelled"
    end
  end

  def order_funds
    
  end

end

app/models/trade.rb
class Trade < ActiveRecord::Base
  belongs_to :order
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  validates_numericality_of :debit, greater_than_or_equal: 0
  validates_numericality_of :debit, less_than_or_equal_to: :check_user_amount

  #Right now its set to server balance cause of fee's not being counted.
  def check_user_amount
    self.user.check_server_balance
  end

  def create_credit_transaction

    if Address.where(address: self.address).present?
      unless Address.find_by(address: self.address).user.id == self.user.id
        Transaction.create(
            credit: self.debit,
            address: self.address,
            transaction_hash: self.transaction_hash,
            currency_type: "BTC",
            processed: true,
            user_id:  Address.find_by(address: self.address).user.id
          )
      end
    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :trades
  has_many :transactions
  has_many :addresses
  has_many :gambles

  def check_balance
    balance = 0
    debit_count = self.transactions.where(credit: 0).count * 0.0001

    self.transactions.each do |t|
      balance += t.credit
      balance -= t.debit
    end
    balance - debit_count
  end 

  def check_server_balance
    btcserver.getbalance self.id.to_s, 0
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @address = Address.new
  end

  def create
    @address = Address.new
    @address.user_id = current_user.id   
    new_address = btcserver.getnewaddress current_user.id.to_s
    @address.address = new_address

    respond_to do |format|
      if @address.save
        format.html { redirect_to pages_finances_path, notice: 'Address was successfully created.' }
        format.json { render action: 'show', status: :created, location: @address }
      else
        format.html { render action: 'new' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  Bitcoin.network = :testnet3
end

app/controllers/gambles_controller.rb
class GamblesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @gambles = Gamble.all
    @gamble = Gamble.new
  end

  def create
    @gamble = Gamble.new(gamble_params)
    @gamble.user_id = current_user.id

    respond_to do |format|
      if @gamble.save
        btcserver.move(@gamble.user_id.to_s, "1337", @gamble.amount, 0)
        @gamble.win_or_lose
        @gamble.payout
        format.html { redirect_to gambles_path, notice: 'Gamble was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gamble }
      else
        format.html { render action: 'new' }
        format.json { render json: @gamble.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def gamble_params
      params.require(:gamble).permit(:amount, :currency_type, :user_id, :won)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to pages_home_path, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to '/', notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to '/' }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:credit, :debit, :exchange_rate, :trade_type, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, only: [:finances]
  
  def home
    @order = Order.new
  end

  def status
  end

  def about
  end

  def contact
  end

  def finances
    @transaction = Transaction.new
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @transactions = current_user.transactions.order(created_at: :desc)
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.currency_type = "BTC"

    respond_to do |format|
      if @transaction.save

        hash = btcserver.sendfrom(@transaction.user_id.to_s,@transaction.address,@transaction.debit.to_f)

        @transaction.transaction_hash = hash
        @transaction.save

        @transaction.create_credit_transaction

        format.html { redirect_to pages_finances_path, notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transaction }
      else
        format.html { redirect_to pages_finances_path, notice: @transaction.errors.messages }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def transaction_params
      params.require(:transaction).permit(:credit, :debit, :address, :transaction_hash, :type, :user_id, :processed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/gambles/index.html.erb
<div id="signup" style="">
  
  <div class="container">
    <div class="row header">
      <div class="col-md-12">
        <h4>Gamble all of your money.</h4>
      </div>
    </div>

    <h5><%= current_user.check_server_balance %></h5>

    <div class="row">
      <div class="col-md-12">
        <div class="wrapper clearfix">
          <div class="formy">
            <div class="row">
              <div class="col-md-12">
                <%= flash[:notice] %>
                <%= simple_form_for @gamble do |f| %>
                  <%= f.error_notification %>
                  <div class="inputs">
                    <%= f.text_field :amount, label: false, class: "form-control", placeholder: 'Amount you wish to gamble' %>
                    <%= f.input :currency_type, class: "form-select", label: false, collection: [ "Ether", "Bitcoin"] %>
                  </div>
                  <div class="actions">
                    <%= f.button :submit, "Gamble!", class: "button", data: {disable_with: "Gambling..."} %>
                  </div>
                <% end %>

              </div>
            </div>                      
          </div>
        </div>
      </div>
      <div class="already-account">

      </div>
    </div>
  </div>

</div>

app/views/layouts/_chart.html.erb
<div id="highstock" style="width:100%; height:400px;"></div>

<script>

$(function() {

  $.getJSON('http://www.highcharts.com/samples/data/jsonp.php?filename=aapl-c.json&callback=?', function(data) {
    // Create the chart
    $('#highstock').highcharts('StockChart', {
      

      rangeSelector : {
        selected : 1
      },

      title : {
        text : 'BTC/ETHER EXCHANGE'
      },
      
      series : [{
        name : 'AAPL',
        data : data,
        tooltip: {
          valueDecimals: 2
        }
      }]
    });
  });

});

</script>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-3 copyright">
        Exchange
      </div>
      <div class="col-sm-6 menu">
        <ul>
          <li class="navbar_item">
            <%= link_to 'Status', pages_status_path %>
          </li>
          <li class="navbar_item">
            <%= link_to 'About', pages_about_path %>
          </li>
          <li class="navbar_item">
            <%= link_to 'Contact', pages_contact_path %>
          </li>
        </ul>
      </div>
      <div class="col-sm-3 social">
        <%= image_tag("social-tw.png") %>
        <%= image_tag("social-dbl.png") %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-inverse normal" role="banner">
  <div class="container">
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("logo.png"), '/', class: "brand", method: :get %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="navbar_item">
              <%= link_to 'My Finance', pages_finances_path %>
            </li>
            <li class="navbar_item">
              <%= link_to 'Gamble', gambles_path %>
            </li>
          <% end %>
          <li class="navbar_item">
            <%= link_to 'Status', pages_status_path %>
          </li>
          <li class="navbar_item">
            <%= link_to 'About', pages_about_path %>
          </li>
          <li class="navbar_item">
            <%= link_to 'Contact', pages_contact_path %>
          </li>

        </ul>
        <ul class="nav navbar-nav navbar-right visible-md visible-lg">
          <% if admin_signed_in? %>
              <li><%= link_to "AdminLogout", destroy_admin_session_path, method: :delete %></li>
          <% elsif user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>s
            <li><%= link_to "Sign in", new_user_session_path %>
            <li><%= link_to "Sign up", new_user_registration_path %>
          <% end %>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_order.html.erb
<div class="row header">
  <div class="col-md-12">
    <h2>Want to place a buy or selling order ?</h2>
  </div>
</div>

<div class="row feature">
  <div class="col-md-6 info">
    <div class="box">
      <div class="row">
        <div class="col-md-12 tabs-wrapper">
          <ul class="nav nav-tabs">
              <li class=""><a href="#messages" data-toggle="tab">Buy BTC/Ether</a></li>
              <li><a href="#settings" data-toggle="tab">Buy Ether/BTC</a></li>
          </ul>

          <div class="tab-content">
            <div class="tab-pane fade" id="messages">
              <div class="col-md-12 info">
              <h5>Buy BTC/Ether</h5>
                <%= simple_form_for @order do |f| %>
                  <%= f.input :debit, label: false, placeholder: "Amount", :input_html => { :style=> 'width: 100px', style: 'margin-bottom: 10px'} %>
                  <%= f.input :exchange_rate, label: false, placeholder: "Price", :input_html => { :style=> 'width: 100px', style: 'margin-bottom: 10px'} %>
                  <%= f.hidden_field :trade_type, value: "buy_btc_eth" %>
                  <%= f.button :submit %>
                <% end %>
              </div>
            </div>
            <div class="tab-pane fade" id="settings">
              <div class="col-md-12 info">
              <h5>Buy Ether/BTC</h5>
                <%= simple_form_for @order do |f| %>
                  <%= f.input :debit, label: false, placeholder: "Amount", :input_html => { :style=> 'width: 100px', style: 'margin-bottom: 10px'} %>
                  <%= f.input :exchange_rate, label: false, placeholder: "Price", :input_html => { :style=> 'width: 100px', style: 'margin-bottom: 10px'} %>
                  <%= f.hidden_field :trade_type, value: "buy_eth_btc" %>
                  <%= f.button :submit %>
                <% end %>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6 info">
    <div class="box">
      <div class="row">
        <div class="col-md-12 tabs-wrapper">
          <ul class="nav nav-tabs">
              <li class=""><a href="#sell_btc_ether" data-toggle="tab">Sell BTC/Ether</a></li>
              <li><a href="#sell_eth_btc" data-toggle="tab">Sell Ether/BTC</a></li>
          </ul>

          <div class="tab-content">
            <div class="tab-pane fade" id="sell_btc_ether">
              <div class="col-md-12 info">
              <h5>Sell BTC/Ether</h5>
                <%= simple_form_for @order do |f| %>
                  <%= f.input :debit, label: false, placeholder: "Amount", :input_html => { :style=> 'width: 100px', style: 'margin-bottom: 10px'} %>
                  <%= f.input :exchange_rate, label: false, placeholder: "Price", :input_html => { :style=> 'width: 100px', style: 'margin-bottom: 10px'} %>
                  <%= f.hidden_field :trade_type, value: "sell_btc_eth"%>
                  <%= f.button :submit %>
                <% end %>
              </div>
            </div>
            <div class="tab-pane fade" id="sell_eth_btc">
              <div class="col-md-12 info">
              <h5>Sell Ether/BTC</h5>
                <%= simple_form_for @order do |f| %>
                  <%= f.input :debit, label: false, placeholder: "Amount", :input_html => { :style=> 'width: 100px', style: 'margin-bottom: 10px'} %>
                  <%= f.input :exchange_rate, label: false, placeholder: "Price", :input_html => { :style=> 'width: 100px', style: 'margin-bottom: 10px'} %>
                  <%= f.hidden_field :trade_type, value: "sell_eth_btc" %>
                  <%= f.button :submit %>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exchange</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tag %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>

</html>

app/views/pages/about.html.erb
<div id="about-us">  
  <div id="info">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>We care about our work</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">          
          <p>
            Whether you want to fill this paragraph with some text like I'm doing right now, this place is perfect to describe some features or anything you want - Canvas has a complete solution for you.
          </p>
          <p>
            You have complete control over the look &amp; feel of your website, we offer the best quality so you take your site up and running in no time.
          </p>
        </div>
        <div class="col-md-6">
          <p>
            Canvas is a simple, developer-friendly way to get your site. Full of features, cool documentation ease of use, lots of pages. We want to help bringing cool stuff to people so they can get their projects faster.
          </p>
          <a href="#" class="join-team button button-small">Join our team</a>
        </div>
      </div>
      <div class="row stats">
        <div class="col-sm-3">
          <strong>13</strong>
          employees
        </div>
        <div class="col-sm-3">
          <strong>10k</strong>
          customers
        </div>
        <div class="col-sm-3">
          <strong>9</strong>
          template pages
        </div>
        <div class="col-sm-3">
          <strong>13k</strong>
          products sold
        </div>
      </div>
      <div class="row team">
        <div class="col-md-12 team-row">
          <img src="images/testimonials/testimonial1.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Eric Smith - CEO">
          <img src="images/testimonials/testimonial2.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Rachel Dawes - PM">
          <img src="images/testimonials/testimonial3.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Henry Hill - Developer">
          <img src="images/testimonials/testimonial4.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Ana Rich - Designer">
          <img src="images/testimonials/testimonial7.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Jessica Welch - Designer">
          <img src="images/testimonials/testimonial8.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Charly - iOS Developer">
        </div>
        <div class="col-md-12 team-row">
          <img src="images/testimonials/testimonial5.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Karen Stewart - PM">
          <img src="images/testimonials/testimonial4.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Charly - iOS Developer">
          <img src="images/testimonials/testimonial7.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Jessica Welch - Designer">
          <img src="images/testimonials/testimonial8.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="John Raynolds - UI/UX">
          <img src="images/testimonials/testimonial3.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Henry Hill - Developer">
          <img src="images/testimonials/testimonial2.jpg" data-toggle="tooltip" title="" alt="testimonial" data-original-title="Rachel Dawes - PM">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div id="contact-us">
  <div id="info">
    <div class="container">
      <div class="row">
        <div class="col-md-8 message">
          <h3>Send us a message</h3>
          <p>
            You can contact us with anything related to Canvas. <br> We'll get in touch with you as soon as possible.
          </p>
          <form role="form">
            <div class="form-group">
                <label for="name">Your name</label>
                <input type="text" class="form-control" id="name">
              </div>
              <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email">
              </div>
              <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" class="form-control" id="phone">
              </div>
              <div class="form-group">
                <label for="message">Your message</label>
                <textarea name="message" class="form-control" id="message" rows="6"></textarea>
              </div>
              <div class="submit">
                <a href="#" class="button button-small">
                  <span>Email us</span>
                </a>
              </div>
          </form>
        </div>
        <div class="col-md-4 contact">
          <div class="address">
            <h3>Our Address</h3>
            <p>
              The Old Road Willington, <br>
              7 Kings Road, <br>
              Southshore, 64890
            </p>
          </div>
          <div class="phone">
            <h3>By Phone</h3>
            <p>
              1-800-346-3344
            </p>
          </div>
          <div class="online-support">
            <strong>Looking for online support?</strong>
            <p>
              Talk to us now with our online chat
            </p>
          </div>
          <div class="social">
            <%= image_tag("fb.png", class: "fb") %>
            <%= image_tag("tw.png", class: "tw") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/finances.html.erb
<div id="home">  
  <div id="features">
    <div class="container">

      <div class="row header">
        <div class="col-md-12">
          <h2>Want to trade your Ether for Bitcoin ?</h2>
          <p>Our exchange does this for you.</p>
        </div>
      </div>

      <div class="row feature">
        <div class="col-md-7 info">
          <div class="box_user_details">
            <h4>User Details</h4>
            <h5>Server Balance</h5>
            <%= btcserver.getbalance current_user.id.to_s, 0 %>
            <h5>DataBase Balance</h5>
            <%= current_user.check_balance %>

            <h5>Recent transactions</h5>

            <table class="table table-striped">
              <tr>
                <th>Address</th>
                <th>Credit</th>
                <th>Debit</th>
              </tr>
              <% current_user.transactions.order(created_at: :desc).first(3).each do |t| %>
                <tr>
                  <td><%= link_to t.address, transaction_path(t) %></td>
                  <td><%= t.credit %></td>
                  <td> <%= t.debit %></td>
                </tr>
              <% end %>
            </table>

          </div>
        </div>

        <div class="col-md-5 info">
          <div class="box">
            <h5>Generate new Adress</h5>
            <p><strong>Last Address:</strong></p>
            <% if current_user.addresses.present? %>
              <% if Bitcoin::valid_address?(current_user.addresses.last.address) == true %>
                <div id="new_address"><%= current_user.addresses.last.address %></div><br>
              <% else %>
                <h5 id="error"> Invalid Address </h5>
              <% end %>
            <% end %>
            <%= button_to "Generate new Adress", addresses_path, class: "button", data: {disable_with: "Generating..."}  %>

            <h6><%= link_to 'List of all Addresses', addresses_path %><h6>
          
          </div>
        </div>

        <div class="col-md-5 info">
          <div class="box">
            <h5>Send BTC to Adress</h5>
            <%= flash[:notice] %>
            <%= form_for(@transaction) do |f| %>
              <div class="field">
                <%= f.text_field :address, placeholder: "BTC Address" %>
              </div><br>
              <div class="field">
                <%= f.text_field :debit, placeholder: "Amount" %>
              </div><br>
              <div class="actions">
                <%= f.submit "Send Coins", id: "button_id", class: "button", data: {disable_with: "Submitting..."} %>
              </div>
            <% end %>
          </div>
        </div>

      </div>

    </div>    
  </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>

  <div id="home">  
    <div id="features">
      <div class="container">
        <div class="row header">
          <div class="col-md-12">
            <h2>Want to trade your Ether for Bitcoin ?</h2>
            <p>Our exchange does this for you.</p>
          </div>
        </div>

        <%= render 'layouts/chart' %>
        <%= render 'layouts/order' %>

      </div>    
    </div>
  </div>

<% else %>

  <div id="home">  
    <div id="features">
      <div class="container">
        <div class="row header">
          <div class="col-md-12">
            <h2>Want to trade your Ether for Bitcoin ?</h2>
            <p>Our exchange does this for you.</p>

            <%= render 'layouts/chart' %>
          </div>
        </div>
      </div>    
    </div>
  </div>
<% end %>

app/views/pages/status.html.erb
<div id="status">  
  <div id="update">
    <div class="container">
      <div class="row header">
        <h3>System Status</h3>
        <p>Current status and incident report</p>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="current-status">
            <span class="updated">
              Updated 2 minutes ago
            </span>
            <div class="status">
              <div class="color yellow"></div>
              All sistems operational
            </div>
            <div class="help">
              Need help? <a href="contactus.html">Contact us</a>.
            </div>            
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default modules">
            <!-- List group -->
            <ul class="list-group">
              <li class="list-group-item">
                Web API
                <div class="status">Operational</div>
              </li>
              <li class="list-group-item">
                Notifications
                <div class="status down">Down</div>
              </li>
              <li class="list-group-item">
                Application Monitoring
                <div class="status">Operational</div>
              </li>
              <li class="list-group-item">
                Browser Plugin
                <div class="status">Operational</div>
              </li>
              <!-- <li class="list-group-item">
                Backoffice Administration
                <div class="status">Operational</div>
              </li> -->
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="messages">
            <h3>Messages</h3>
            <div class="date">
              <div class="day">Today</div>
              <p class="ok">
                All systems operational
              </p>
            </div>
            <div class="date">
              <div class="day">Yesterday, October 25 2013</div>
              <p class="ok">
                All systems operational
              </p>
            </div>
            <div class="date">
              <div class="day">October 04 2013</div>
              <p class="ok">
                All systems operational
              </p>
            </div>
            <div class="date">
              <div class="day">October 03 2013</div>
              <p class="ok">
                All systems operational
              </p>
            </div>
            <div class="date">
              <div class="day">October 02 2013</div>
              <p class="issues">
                Application deployment issues
              </p>
              <p class="update">
                <strong>Resolved:</strong>
                We fixed the issues monitoring status, downtime was between 1pm and 5pm PT.
              </p>
              <p class="update">
                <strong>Investigating:</strong>
                We identified some issues deploying some applications and monitoring their status.
              </p>
            </div>
          </div>
          <div class="full-history">
            <a href="#">
              ← See full incident history
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Created at</th>
    <th>Address</th>
    <th>Credit</th>
    <th>Debit</th>
    <th>txid</th>

  </tr>
    <% @transactions.each do |t|  %>
      <tr>
        <td><%= t.created_at %></td>
        <td><%= t.address %></td>
        <td><%= t.credit %></td>
        <td>- <%= t.debit %></td>
        <td><%= t.transaction_hash %></td>
      </tr>
    <% end %>   
</table>

app/views/transactions/show.html.erb
<div id="home">  
  <div id="features">
    <div class="container">

      <div class="row header">
        <div class="col-md-12">
          <h2>Want to trade your Ether for Bitcoin ?</h2>
          <p>Our exchange does this for you.</p>
        </div>
      </div>

      <div class="row feature">
        <div class="col-md-12 info">
          <div class="box">
            <h4>Transaction Details</h4>
            <% t = btcserver.gettransaction @transaction.transaction_hash %>
            <ul>  
              <li>Send to Address: <%= t["details"][0]["address"] %></li>
              <li>Category: <%= t["details"][0]["category"] %></li>
              category klopt nog niet overal.
              <li>Amount: <%= t["details"][0]["amount"] %></li>
              <li>Fee: <%=  t["fee"] %></li>
              <li>Confirmations: <%= t["confirmations"] %></li>
            </ul>
  
          </div>
        </div>
    </div>    
  </div>
</div>